apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications-sleepr
  name: notifications-sleepr
spec:
  ports:
  - name: "tcp"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: notifications-sleepr
  type: ClusterIP
